HH-81977 updated jersey version to 2.27
hhru/webhcat-java-client pull request #2
Opened 2018-08-16 14:44 UTC by troy4eg

2018-08-16 16:20 UTC, sergey-podunov requested changes

2018-08-16 16:26 UTC, troy4eg commented on src/test/java/ru/hh/hadoop/webhcat/hive/WebHCatClientTest.java
> +    Map<String, String> body = response.readEntity(Map.class);
потому что было принято решение выпилить jersey-test-client везде где можно

2018-08-16 16:27 UTC, troy4eg commented on pom.xml
> +            <artifactId>jaxb-api</artifactId>
собирается != работает рантайм

2018-08-16 16:29 UTC, troy4eg commented on pom.xml
> +            <scope>provided</scope>
да, точно
странно что до этого вообще никакого скоупа не стояло
а как у меня провайдед проставился вообще хз, заменю

2018-08-16 16:46 UTC, sergey-podunov commented on src/main/java/ru/hh/hadoop/webhcat/hdfs/WebHDFSClient.java
> +public class WebHDFSClient {
ну не знаю, формально это разные сервисы в hadoop, теоретически HCat может и не быть

2018-08-16 16:50 UTC, sergey-podunov commented on pom.xml
> +            <artifactId>jaxb-api</artifactId>
а до этого как работало? вроде xml нигде не биндится тут

2018-08-16 16:57 UTC, sergey-podunov commented on src/main/java/ru/hh/hadoop/webhcat/hdfs/WebHDFSClient.java
> +public class WebHDFSClient {
тогда и репу https://github.com/hhru/web-hdfs-java-client прибить надо

2018-08-16 17:09 UTC, troy4eg commented on src/main/java/ru/hh/hadoop/webhcat/hdfs/WebHDFSClient.java
> +public class WebHDFSClient {
основная история в том, что используются обе либо только в одном сервисе и вместе

п.с. прибьем

2018-08-16 17:13 UTC, troy4eg commented on src/main/java/ru/hh/hadoop/webhcat/WebHCatClient.java
> -    mapper.setSerializationInclusion(JsonSerialize.Inclusion.NON_NULL);
этот момент поправил

2018-08-17 10:52 UTC, sergey-podunov approved these changes

2018-08-17 11:48 UTC, merged